theme: minima

author:
  name: GitHub User
  email: your-email@domain.com

title: Your awesome title

description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%Y-%m-%d"
  header_pages:
    - about.md
    - index.md
  social_links:
    twitter: piscilus
